import SwiftUI
import SwiftData

/// Core product screen — shows who you're talking to and what to say.
///
/// Display states:
///   No notes  — generic prompts only, no context section.
///   Has notes — most recent note shown as "Last time" context;
///               additional notes shown in a Notes section.
///
/// Prompts are generated by PromptEngine (Phase 4). Refresh rotates
/// through the engine's full template pool for the current person context.
struct PersonView: View {
    let person: Person

    @Environment(\.modelContext) private var modelContext
    @State private var showCapture = false
    @State private var currentPrompts: [Prompt] = []

    // Notes sorted newest first, derived from the @Observable person.
    private var sortedNotes: [Note] {
        person.notes.sorted { $0.createdAt > $1.createdAt }
    }

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 0) {
                personHeader
                    .padding(.horizontal, AppSpacing.md)
                    .padding(.top, AppSpacing.md)

                if !sortedNotes.isEmpty {
                    contextSection
                        .padding(.horizontal, AppSpacing.md)
                        .padding(.top, AppSpacing.lg)
                }

                promptsSection
                    .padding(.top, AppSpacing.xl)

                if sortedNotes.count > 1 {
                    notesSection
                        .padding(.top, AppSpacing.xl)
                }

                captureSection
                    .padding(.horizontal, AppSpacing.md)
                    .padding(.top, AppSpacing.lg)
            }
            .padding(.bottom, AppSpacing.xxl)
        }
        .background(AppColors.background)
        .navigationTitle(person.displayName)
        .navigationBarTitleDisplayMode(.inline)
        .onAppear {
            PersonRepository.markOpened(person, in: modelContext)
            generatePrompts()
        }
        // Re-generate when a note is added via the capture sheet.
        .onChange(of: person.notes.count) { _, _ in
            generatePrompts()
        }
        .sheet(isPresented: $showCapture) {
            CaptureView(person: person, isSheet: true)
        }
    }

    // MARK: - Prompt generation

    private func generatePrompts() {
        currentPrompts = PromptEngine.prompts(for: person, sortedNotes: sortedNotes)
    }

    private func rotatePrompts() {
        currentPrompts = PromptEngine.refreshedPrompts(
            for: person,
            sortedNotes: sortedNotes,
            excluding: currentPrompts
        )
    }

    // MARK: - Sections

    private var personHeader: some View {
        HStack(spacing: AppSpacing.md) {
            AvatarView(initials: person.initials, size: AppSize.avatarLG)

            VStack(alignment: .leading, spacing: AppSpacing.xxs) {
                Text(person.displayName)
                    .font(AppTypography.title2)
                    .foregroundStyle(AppColors.label)

                if let label = person.lastInteractionLabel {
                    Text("Last spoke \(label)")
                        .font(AppTypography.subheadline)
                        .foregroundStyle(AppColors.secondaryLabel)
                }
            }

            Spacer()
        }
    }

    /// Shows the most recent note as "Last time" context.
    @ViewBuilder
    private var contextSection: some View {
        if let contextText = person.lastContext {
            VStack(alignment: .leading, spacing: AppSpacing.sm) {
                SectionHeader("Last time")

                Text(contextText)
                    .font(AppTypography.body)
                    .foregroundStyle(AppColors.secondaryLabel)
                    .padding(AppSpacing.md)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .background(AppColors.secondaryBackground)
                    .clipShape(RoundedRectangle(cornerRadius: AppRadius.md))
            }
        }
    }

    private var promptsSection: some View {
        VStack(alignment: .leading, spacing: AppSpacing.sm) {
            SectionHeader("Try asking")
                .padding(.horizontal, AppSpacing.md)

            if currentPrompts.isEmpty {
                // Shown briefly before onAppear fires — invisible in practice.
                Color.clear.frame(height: 0)
            } else {
                VStack(spacing: AppSpacing.sm) {
                    ForEach(currentPrompts) { prompt in
                        PromptChip(text: prompt.text)
                    }
                }
                .padding(.horizontal, AppSpacing.md)

                Button(action: rotatePrompts) {
                    Label("New ideas", systemImage: "arrow.clockwise")
                        .font(AppTypography.footnote)
                        .foregroundStyle(AppColors.tertiaryLabel)
                }
                .buttonStyle(.plain)
                .padding(.horizontal, AppSpacing.md)
                .padding(.top, AppSpacing.xs)
            }
        }
    }

    /// Shows notes beyond the first one already surfaced in contextSection.
    private var notesSection: some View {
        VStack(alignment: .leading, spacing: AppSpacing.sm) {
            SectionHeader("Notes")
                .padding(.horizontal, AppSpacing.md)

            VStack(spacing: AppSpacing.sm) {
                ForEach(Array(sortedNotes.dropFirst())) { note in
                    NoteCard(note: note)
                }
            }
            .padding(.horizontal, AppSpacing.md)
        }
    }

    private var captureSection: some View {
        Button {
            showCapture = true
        } label: {
            HStack(spacing: AppSpacing.sm) {
                Image(systemName: "plus.circle")
                    .font(.system(size: 17, weight: .medium))
                Text("Add something (optional)")
                    .font(AppTypography.callout)
            }
            .foregroundStyle(AppColors.secondaryLabel)
            .frame(maxWidth: .infinity)
            .padding(.vertical, AppSpacing.md)
            .background(AppColors.secondaryBackground)
            .clipShape(RoundedRectangle(cornerRadius: AppRadius.md))
        }
        .buttonStyle(.plain)
    }
}

// MARK: - NoteCard

private struct NoteCard: View {
    let note: Note

    var body: some View {
        Text(note.rawText)
            .font(AppTypography.subheadline)
            .foregroundStyle(AppColors.secondaryLabel)
            .padding(AppSpacing.md)
            .frame(maxWidth: .infinity, alignment: .leading)
            .background(AppColors.secondaryBackground)
            .clipShape(RoundedRectangle(cornerRadius: AppRadius.sm))
    }
}

// MARK: - Previews

#Preview("With Notes") {
    let config = ModelConfiguration(isStoredInMemoryOnly: true)
    let container = try! ModelContainer(for: Person.self, Note.self, configurations: config)
    let ctx = container.mainContext

    let sarah = Person(displayName: "Sarah Chen")
    sarah.lastOpenedAt = Calendar.current.date(byAdding: .day, value: -14, to: Date())
    ctx.insert(sarah)

    let n1 = Note(rawText: "Starting new job at Google next Monday")
    n1.person = sarah
    ctx.insert(n1)

    let n2 = Note(rawText: "Excited but nervous about the team")
    n2.person = sarah
    ctx.insert(n2)

    try! ctx.save()

    return NavigationStack { PersonView(person: sarah) }
        .modelContainer(container)
}

#Preview("No Notes") {
    let config = ModelConfiguration(isStoredInMemoryOnly: true)
    let container = try! ModelContainer(for: Person.self, Note.self, configurations: config)
    let person = Person(displayName: "Riley Morgan")
    container.mainContext.insert(person)

    return NavigationStack { PersonView(person: person) }
        .modelContainer(container)
}
